// <auto-generated />
using System;
using CIS174_TestCoreApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CIS174_TestCoreApp.Migrations
{
    [DbContext(typeof(Assgn10Context))]
    [Migration("20191105045303_InitialDatabaseSetup")]
    partial class InitialDatabaseSetup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CIS174_TestCoreApp.Entity.Assgn10Accomplishment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Assgn10Personid");

                    b.Property<DateTime>("DateOfAccomplishment");

                    b.Property<string>("Name");

                    b.Property<int>("PersonId");

                    b.HasKey("id");

                    b.HasIndex("Assgn10Personid");

                    b.ToTable("Accomplishments");
                });

            modelBuilder.Entity("CIS174_TestCoreApp.Entity.Assgn10Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("City");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.Property<string>("SetOfAccomplishments");

                    b.Property<string>("State");

                    b.HasKey("id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("CIS174_TestCoreApp.Entity.Assgn10Accomplishment", b =>
                {
                    b.HasOne("CIS174_TestCoreApp.Entity.Assgn10Person")
                        .WithMany("Accomplishments")
                        .HasForeignKey("Assgn10Personid");
                });
#pragma warning restore 612, 618
        }
    }
}
